width = 1024
height = 768
spriteSize = 32
tilesX = int(width * 2 / spriteSize)
tilesY = int(height * 2 / spriteSize)
roomMax = 50
roomMin = 20
roomMaxWidth  = 4
roomMinWidth  = 2
roomMaxHeight = 4
roomMinHeight = 2
cameraOffsetX = -int(width / 2)
cameraOffsetY = -int(height / 2)
switchWallStatus = 0
cameraSpeed = 5
debug = 0
