width = 1024
height = 768
spriteSize = 32
zoom = spriteSize
tilesX = int(width * 2 / spriteSize)
tilesY = int(height * 2 / spriteSize)
roomMax = 25
roomMin = 10
roomMaxWidth  = 6
roomMinWidth  = 4
roomMaxHeight = 6
roomMinHeight = 4
cameraOffsetX = -int(width / 2)*0
cameraOffsetY = -int(height / 2)*0
switchWallStatus = 0
cameraSpeed = 15 * spriteSize # since frametime is now being calculated
debug = 0
