width = 1024
height = 768
tilesX = int(width * 2 / 32)
tilesY = int(height * 2 / 32)
roomMax = 50
roomMin = 20
roomMaxWidth  = 4
roomMinWidth  = 2
roomMaxHeight = 4
roomMinHeight = 2
cameraOffsetX = -int(width / 1)
cameraOffsetY = -int(height / 1)
switchWallStatus = 0
cameraSpeed = 5
debug = 0
